### Exercice 1:

Write a function that takes a string, and two indexes (integers), and returns a slice of that string as well as the length of the string.
Call the function, and store the results in two variables

In [20]:
#Declare the function

def slice_of_string(ch,i,x):
    result = ch[i:x+1]
    print("the result is: ",result)
    print("length of result is: ",len(result))
    

#Call the function
slice_of_string("hello imane it is me",5,9)






the result is:   iman
length of result is:  5


### Exercice 2:

1. Write a function that takes two arguments, and returns the sum of the two.
2. Call the function with the values 1 and 2.1, then check the type of the result.
3. Call the function with the values False and 2, then check the type of the result.

In [25]:
#Declare the function
def summ(x,y):
    return x + y
    

#Call with the values 1 and two
x = summ(1,2.1)
q = summ(False,2)
print("the first case is : ",x,"the second case is : ",q)


#Check the type of the result
print(type(x))
print(type(q))

the first case is :  3.1 the second case is :  2
<class 'float'>
<class 'int'>


### Exercice 3:

Write a function that takes a string and returns a dictionary containing character frequency.

*example*

    string sample: 'test'
    
    expected result: {'t':2, 'e':1, 's':1}

In [28]:
#Declare the function
test = 'asaada'
d = {i : test.count(i) for i in test}

#Print the result
print(d)

4
{'a': 4, 's': 1, 'd': 1}


### Exercice 4:

Given two lists, iterate both lists simultaniously, such the first list would display item in original order and the second list in reverse order

*example*:

In [3]:
from lib import print_orl #this is a lib you dont have access to
print_orl([1,2,3],[1,2,3])

1 3
2 2
3 1


In [14]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([3,2,1])
for x,y in zip(np.nditer(arr1),np.nditer(arr2[::-1])):
  print(x,y)

  




1 3
2 2
3 1


### Exercice 5:

Given two 2d arrays, stack them horizontally.

*example:*

In [18]:
import numpy as np

#The input
a = np.ones((1, 10)).reshape(2, -1)
b = np.zeros((1, 10)).reshape(2, -1)

#Try to print input
print (a,b)

#concatenate horizontally
#output shoul look like:     array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
#                                  [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])

np.concatenate((a, b), axis=1)




[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])

### exercice 6:

Create the following patterns using the bellow arrays a and b, and numpy functions:

In [57]:
a = np.arange(3)
b = np.ones((3,3,3))


#output1 the following array: array([0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])



#output2 the follwing array: array([[[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]]])

a = np.array([1, 2, 3])
#output3 array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.]])
b = np.ones((1,3,9))



SyntaxError: invalid syntax (987778912.py, line 21)