### Exercice 1:

Write a function that takes a string, and two indexes (integers), and returns a slice of that string as well as the length of the string.
Call the function, and store the results in two variables

In [21]:
def slice(word, i, j):
    length=abs(i-j)
    if i<j:
        myslice= word[i:j] 
    else:
        myslice= word[j:i] 
    print('My slice: {} \nLength: {}'.format(myslice, length))
slice("Myword", 6,2)

    

### Exercice 2:

1. Write a function that takes two arguments, and returns the sum of the two.
2. Call the function with the values 1 and 2.1, then check the type of the result.
3. Call the function with the values False and 2, then check the type of the result.

In [24]:
def mysum(a,b):
    c=a+b
    return c
a=mysum(1,2.1)
print(a, type(a))
a=mysum(False,2)
print(a, type(a))

3.1 <class 'float'>
2 <class 'int'>


### Exercice 3:

Write a function that takes a string and returns a dictionary containing character frequency.

*example*

    string sample: 'test'
    
    expected result: {'t':2, 'e':1, 's':1}

In [52]:
def myfrequency(mystring):
    info = {}
    for x in mystring:
        info[x]=mystring.count(x)
    print(info)
    
myfrequency('test')

{'t': 2, 'e': 1, 's': 1}


### Exercice 4:

Given two lists, iterate both lists simultaniously, such the first list would display item in original order and the second list in reverse order

*example*:

In [3]:
from lib import print_orl #this is a lib you dont have access to
print_orl([1,2,3],[1,2,3])

1 3
2 2
3 1


In [55]:
liste1=[1,2]
liste2=[1,2]
for i in range (len(liste1)):
    print(liste1[i], liste2[len(liste2)-i-1])

1 2
2 1


### Exercice 5:

Given two 2d arrays, stack them horizontally.

*example:*

In [66]:
import numpy as np

#The input
a = np.ones((1, 10)).reshape(2, -1)
b = np.zeros((1, 10)).reshape(2, -1)

#Try to print input
print(a)
print("bela")
print(b)

#concatenate horizontally
#output should look like:     array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
#                                   [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])

np.concatenate((a[0], b[0], a[1], b[1]))



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
bela
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0.])

### exercice 6:

Create the following patterns using the bellow arrays a and b, and numpy functions:

In [2]:
import numpy as np
a = np.arange(3)
b = np.ones((3,3,3))

#print(a)
#print("fff")
#print(b)

#output1 the following array: array([0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])
c=np.concatenate((np.repeat(a,3),a,a,a))
print(c)

q = np.array([[[1., 2., 3.],
                                  [1., 2., 3.],
                                  [1., 2., 3.]],

                                  [[1., 2., 3.],
                                    [1., 2., 3.],
                                    [1., 2., 3.]],

                                    [[1., 2., 3.],
                                   [1., 2., 3.],
                                   [1., 2., 3.]]])

print(q.shape)
x= a + b[0]
x=np.concatenate((x,x,x)).reshape(3,3,3)
print(x)
#output3 array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

v=b.reshape(3,9)
print(v)

[0 0 0 1 1 1 2 2 2 0 1 2 0 1 2 0 1 2]
(3, 3, 3)
[[[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
